apiVersion: agents.algoluna.com/v1alpha1
kind: Agent
metadata:
  name: hello-agent-test
spec:
  type: hello-agent
  image: localhost:32000/hello-agent:latest
  runOnce: true
  env:
    - name: LOG_LEVEL
      value: "debug"
    - name: TEST_MODE
      value: "true"
