apiVersion: agents.algoluna.com/v1alpha1
kind: Agent
metadata:
  name: hello-agent
spec:
  type: hello
  image: "hello-agent:latest"
  
  # Optional configuration with sensible defaults
  runOnce: false
  maxRestarts: -1
  ttl: 0
  
  # Environment-specific configurations
  environments:
    dev:
      registry: "localhost:32000"
      cluster: "minikube"
      env:
        - name: DEBUG
          value: "true"
    
    microk8s:
      registry: "localhost:32000"
      cluster: "microk8s"
    
    prod:
      registry: "prod-registry.example.com"
      cluster: "prod-cluster"
      env:
        - name: DEBUG
          value: "false"
