{{- if and .Values.postgresql.enabled (not .Values.postgresql.external) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentbox.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP # Only needs to be accessible within the cluster
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: tcp-postgresql
  selector:
    # Selects the pods managed by the StatefulSet
    app.kubernetes.io/name: {{ include "agentbox.name" . }}-postgresql 
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgresql
{{- end }}
