{{- if .Values.globalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: valkey-admin-secret
  namespace: agentbox-system
type: Opaque
stringData:
  VALKEY_ADMIN_USER: {{ .Values.valkeyAdmin.user | quote }}
  VALKEY_ADMIN_PASSWORD: {{ .Values.valkeyAdmin.password | quote }}
{{- end }}
