apiVersion: agents.algoluna.com/v1alpha1
kind: Agent
metadata:
  name: chatbot-agent
spec:
  type: chatbot
  image: "chatbot-agent:latest"
  runOnce: false
  maxRestarts: -1
  ttl: 0
  env:
    - name: MODEL_NAME
      value: "gemini-pro"
    
  # Environment configurations
  environments:
    # Local microk8s environment
    microk8s:
      registry: "localhost:32000"
