apiVersion: agents.algoluna.com/v1alpha1
kind: Agent
metadata:
  name: chatbot-agent
spec:
  type: chatbot
  image: "chatbot-agent:latest"
  
  # Optional configuration with sensible defaults
  runOnce: false
  maxRestarts: -1
  ttl: 0
  
  # Required agent-specific configuration
  env:
    - name: MODEL_NAME
      value: "gemini-pro"
  
  # Environment-specific configurations
  environments:
    dev:
      registry: "localhost:32000"
      cluster: "minikube"
      env:
        - name: DEBUG
          value: "true"
        - name: MODEL_NAME
          value: "gemini-pro"
    
    microk8s:
      registry: "localhost:32000"
      cluster: "microk8s"
    
    prod:
      registry: "prod-registry.example.com"
      cluster: "prod-cluster"
      env:
        - name: DEBUG
          value: "false"
        - name: MODEL_NAME
          value: "gemini-flash-2.0"
