apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agentbox.fullname" . }}-agent-messaging
  labels:
    {{- include "agentbox.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agentbox.fullname" . }}-agent-messaging
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated # Allow all authenticated users to send messages
